apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo

resources:
  - gitops-namespace.yaml
  - gitops-configmap.yaml
  - gitops-mysql-deployment.yaml
  - gitops-mysql-service.yaml
  - gitops-deployment.yaml
  - gitops-service.yaml

images:
<<<<<<< HEAD
  - name: docker.io/s4ngg/demo
    newName: docker.io/s4ngg/demo
    newTag: ddf0fe6
=======
  - name: docker.io/koreanirsa/demo
    newName: docker.io/koreanirsa/demo
    newTag: ddf0fe6
>>>>>>> 72f25b853fb30fcf1f30fa63743d1015b1f44063
