apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo

resources:
  - gitops-namespace.yaml
  - gitops-configmap.yaml
  - gitops-mysql-deployment.yaml
  - gitops-mysql-service.yaml
  - gitops-deployment.yaml
  - gitops-service.yaml

images:
  - name: docker.io/s4ngg/demo
    newName: docker.io/s4ngg/demo
    newTag: ddf0fe6
